# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service_stub/service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aservice_stub/service.proto\x12\x03idm\"m\n\tUserPatch\x12\r\n\x05token\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x03\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\x12\x13\n\x0b\x61\x63tion_role\x18\x05 \x01(\t\x12\x0c\n\x04role\x18\x06 \x01(\t\")\n\x06Result\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"#\n\x06UserId\x12\r\n\x05token\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x03\".\n\x08UserData\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"K\n\x08UserBody\x12\r\n\x05token\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\"\x16\n\x05Token\x12\r\n\x05token\x18\x01 \x01(\t2\x8d\x02\n\nIdmService\x12*\n\nCreateUser\x12\r.idm.UserBody\x1a\x0b.idm.Result\"\x00\x12%\n\x05Login\x12\r.idm.UserData\x1a\x0b.idm.Result\"\x00\x12*\n\rValidateToken\x12\n.idm.Token\x1a\x0b.idm.Result\"\x00\x12)\n\x0c\x44\x65stroyToken\x12\n.idm.Token\x1a\x0b.idm.Result\"\x00\x12(\n\nDeleteUser\x12\x0b.idm.UserId\x1a\x0b.idm.Result\"\x00\x12+\n\nUpdateUser\x12\x0e.idm.UserPatch\x1a\x0b.idm.Result\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_stub.service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERPATCH']._serialized_start=35
  _globals['_USERPATCH']._serialized_end=144
  _globals['_RESULT']._serialized_start=146
  _globals['_RESULT']._serialized_end=187
  _globals['_USERID']._serialized_start=189
  _globals['_USERID']._serialized_end=224
  _globals['_USERDATA']._serialized_start=226
  _globals['_USERDATA']._serialized_end=272
  _globals['_USERBODY']._serialized_start=274
  _globals['_USERBODY']._serialized_end=349
  _globals['_TOKEN']._serialized_start=351
  _globals['_TOKEN']._serialized_end=373
  _globals['_IDMSERVICE']._serialized_start=376
  _globals['_IDMSERVICE']._serialized_end=645
# @@protoc_insertion_point(module_scope)
